// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type SnoopEvent struct {
	_         structs.HostLayout
	CgroupId  uint64
	Pid       uint32
	SyscallNr uint32
	Path      [4096]int8
}

// LoadSnoop returns the embedded CollectionSpec for Snoop.
func LoadSnoop() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_SnoopBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Snoop: %w", err)
	}

	return spec, err
}

// LoadSnoopObjects loads Snoop and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*SnoopObjects
//	*SnoopPrograms
//	*SnoopMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadSnoopObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadSnoop()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// SnoopSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type SnoopSpecs struct {
	SnoopProgramSpecs
	SnoopMapSpecs
	SnoopVariableSpecs
}

// SnoopProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type SnoopProgramSpecs struct {
	TraceExecve     *ebpf.ProgramSpec `ebpf:"trace_execve"`
	TraceExecveat   *ebpf.ProgramSpec `ebpf:"trace_execveat"`
	TraceFaccessat  *ebpf.ProgramSpec `ebpf:"trace_faccessat"`
	TraceFaccessat2 *ebpf.ProgramSpec `ebpf:"trace_faccessat2"`
	TraceNewfstatat *ebpf.ProgramSpec `ebpf:"trace_newfstatat"`
	TraceOpenat     *ebpf.ProgramSpec `ebpf:"trace_openat"`
	TraceOpenat2    *ebpf.ProgramSpec `ebpf:"trace_openat2"`
	TraceReadlinkat *ebpf.ProgramSpec `ebpf:"trace_readlinkat"`
	TraceStatx      *ebpf.ProgramSpec `ebpf:"trace_statx"`
}

// SnoopMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type SnoopMapSpecs struct {
	DroppedEvents *ebpf.MapSpec `ebpf:"dropped_events"`
	Events        *ebpf.MapSpec `ebpf:"events"`
	Heap          *ebpf.MapSpec `ebpf:"heap"`
	TracedCgroups *ebpf.MapSpec `ebpf:"traced_cgroups"`
}

// SnoopVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type SnoopVariableSpecs struct {
}

// SnoopObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadSnoopObjects or ebpf.CollectionSpec.LoadAndAssign.
type SnoopObjects struct {
	SnoopPrograms
	SnoopMaps
	SnoopVariables
}

func (o *SnoopObjects) Close() error {
	return _SnoopClose(
		&o.SnoopPrograms,
		&o.SnoopMaps,
	)
}

// SnoopMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadSnoopObjects or ebpf.CollectionSpec.LoadAndAssign.
type SnoopMaps struct {
	DroppedEvents *ebpf.Map `ebpf:"dropped_events"`
	Events        *ebpf.Map `ebpf:"events"`
	Heap          *ebpf.Map `ebpf:"heap"`
	TracedCgroups *ebpf.Map `ebpf:"traced_cgroups"`
}

func (m *SnoopMaps) Close() error {
	return _SnoopClose(
		m.DroppedEvents,
		m.Events,
		m.Heap,
		m.TracedCgroups,
	)
}

// SnoopVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadSnoopObjects or ebpf.CollectionSpec.LoadAndAssign.
type SnoopVariables struct {
}

// SnoopPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadSnoopObjects or ebpf.CollectionSpec.LoadAndAssign.
type SnoopPrograms struct {
	TraceExecve     *ebpf.Program `ebpf:"trace_execve"`
	TraceExecveat   *ebpf.Program `ebpf:"trace_execveat"`
	TraceFaccessat  *ebpf.Program `ebpf:"trace_faccessat"`
	TraceFaccessat2 *ebpf.Program `ebpf:"trace_faccessat2"`
	TraceNewfstatat *ebpf.Program `ebpf:"trace_newfstatat"`
	TraceOpenat     *ebpf.Program `ebpf:"trace_openat"`
	TraceOpenat2    *ebpf.Program `ebpf:"trace_openat2"`
	TraceReadlinkat *ebpf.Program `ebpf:"trace_readlinkat"`
	TraceStatx      *ebpf.Program `ebpf:"trace_statx"`
}

func (p *SnoopPrograms) Close() error {
	return _SnoopClose(
		p.TraceExecve,
		p.TraceExecveat,
		p.TraceFaccessat,
		p.TraceFaccessat2,
		p.TraceNewfstatat,
		p.TraceOpenat,
		p.TraceOpenat2,
		p.TraceReadlinkat,
		p.TraceStatx,
	)
}

func _SnoopClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed snoop_arm64_bpfel.o
var _SnoopBytes []byte
